compile:
	javac -d classes -sourcepath src src/org/ioopm/calculator/Calculator.java

run:
	java -cp classes org.ioopm.calculator.Calculator

compile_test:
	javac -d classes -sourcepath src src/Test.java

run_test:
	java -cp classes Test

clean:
	rm -rf classes
